services:
    CSL\Module\LoggerBundle\CslLoggerFactory:
        arguments:
            $parameterBag: '@parameter_bag'
            $handlerFactory: '@CSL\Module\LoggerBundle\Handler\Factory\HandlerFactoryInterface'

    csl.logger:
        class: Monolog\Logger
        factory: ['@CSL\Module\LoggerBundle\CslLoggerFactory', 'createLogger']
        shared: true
        tags: [{ name: kernel.reset, method: reset }]

    CSL\Module\LoggerBundle\CslLogger\CslLogger:
        arguments:
            $logger: '@csl.logger'

    CSL\Module\LoggerBundle\CslLogger\CslLoggerInterface:
        alias: CSL\Module\LoggerBundle\CslLogger\CslLogger
